script:
  - npm test && cd ..
  - cd ./server && npm test
  - docker build -t server .
  - cd ../client && docker build -t client .
  - cd ../db && docker build -t db .  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag server $DOCKER_USER/server:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/server:$TRAVIS_BUILD_NUMBER
  - docker tag server $DOCKER_USER/server:latest
  - docker push $DOCKER_USER/client:latest
  - docker tag client $DOCKER_USER/client:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/client:$TRAVIS_BUILD_NUMBER
  - docker tag client $DOCKER_USER/client:latest
  - docker push $DOCKER_USER/client:latest
  - docker tag db $DOCKER_USER/db:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/db:$TRAVIS_BUILD_NUMBER
  - docker tag db $DOCKER_USER/db:latest
  - docker push $DOCKER_USER/db:latest
