language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - cd ./server && npm install
  - cd .. && cd ./client && npm install
script:
  - npm test && cd ..
  - cd ./server && npm test
  - docker build -t server .
  - cd ../client && docker build -t client .
  - cd ../db && docker build -t db .  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag node-svr $DOCKER_USER/node-svr:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/node-svr:$TRAVIS_BUILD_NUMBER
  - docker tag node-svr $DOCKER_USER/node-svr:latest
  - docker push $DOCKER_USER/react-client:latest
  - docker tag react-client $DOCKER_USER/react-client:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/react-client:$TRAVIS_BUILD_NUMBER
  - docker tag react-client $DOCKER_USER/react-client:latest
  - docker push $DOCKER_USER/react-client:latest
  - docker tag node-react-db $DOCKER_USER/node-react-db:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/node-react-db:$TRAVIS_BUILD_NUMBER
  - docker tag node-react-db $DOCKER_USER/node-react-db:latest
  - docker push $DOCKER_USER/node-react-db:latest
